// TOEIC 400-600 帯の語彙。w: 語 / m: 意味 / ex: 例文 / exJa: 例文訳
// 精錬画面の誤答選択肢は、このリスト内の他の語の意味から自動生成する。
window.SHINMYAKU_WORDS = [
  { w: "achieve", m: "達成する", ex: "We achieved our sales target last quarter.", exJa: "私たちは前四半期に売上目標を達成した。" },
  { w: "afford", m: "余裕がある、買える", ex: "We cannot afford a new copier this year.", exJa: "今年は新しいコピー機を買う余裕がない。" },
  { w: "agenda", m: "議題、予定表", ex: "Please send me the agenda before the meeting.", exJa: "会議の前に議題を送ってください。" },
  { w: "annual", m: "年次の、毎年の", ex: "The annual report will be published in May.", exJa: "年次報告書は5月に公開される。" },
  { w: "apply", m: "応募する、適用する", ex: "She applied for a position in the sales department.", exJa: "彼女は営業部の職に応募した。" },
  { w: "appointment", m: "予約、約束", ex: "I have an appointment with the dentist at three.", exJa: "3時に歯医者の予約がある。" },
  { w: "approve", m: "承認する", ex: "The manager approved my vacation request.", exJa: "部長は私の休暇申請を承認した。" },
  { w: "arrange", m: "手配する、整える", ex: "Could you arrange a taxi to the airport?", exJa: "空港までのタクシーを手配してもらえますか。" },
  { w: "attach", m: "添付する、取り付ける", ex: "I attached the invoice to this email.", exJa: "このメールに請求書を添付しました。" },
  { w: "attend", m: "出席する", ex: "About fifty people attended the conference.", exJa: "約50人がその会議に出席した。" },
  { w: "available", m: "利用できる、都合がつく", ex: "The meeting room is available after two.", exJa: "その会議室は2時以降なら使える。" },
  { w: "avoid", m: "避ける", ex: "Take the side street to avoid heavy traffic.", exJa: "渋滞を避けるには脇道を通るといい。" },
  { w: "balance", m: "残高、均衡", ex: "Please check the balance of your account.", exJa: "口座の残高を確認してください。" },
  { w: "benefit", m: "利点、手当", ex: "The new plan offers better health benefits.", exJa: "新しい制度はより良い健康手当を提供する。" },
  { w: "bill", m: "請求書、紙幣", ex: "The electricity bill arrived this morning.", exJa: "電気の請求書が今朝届いた。" },
  { w: "branch", m: "支店、枝", ex: "Our company opened a branch in Osaka.", exJa: "当社は大阪に支店を開設した。" },
  { w: "budget", m: "予算", ex: "The project went over budget by ten percent.", exJa: "そのプロジェクトは予算を10%超過した。" },
  { w: "cancel", m: "取り消す", ex: "They canceled the flight because of the storm.", exJa: "嵐のため彼らは欠航にした。" },
  { w: "candidate", m: "候補者", ex: "We interviewed six candidates for the job.", exJa: "その職に6人の候補者を面接した。" },
  { w: "charge", m: "請求する、料金", ex: "The hotel charges extra for parking.", exJa: "そのホテルは駐車料金を別に請求する。" },
  { w: "client", m: "顧客、依頼人", ex: "Our client asked for a discount.", exJa: "顧客が値引きを求めてきた。" },
  { w: "colleague", m: "同僚", ex: "I discussed the plan with my colleagues.", exJa: "私は同僚たちとその計画を話し合った。" },
  { w: "commute", m: "通勤する", ex: "He commutes to the office by train.", exJa: "彼は電車で会社に通勤している。" },
  { w: "compare", m: "比較する", ex: "Let's compare the two proposals carefully.", exJa: "2つの提案を慎重に比較しよう。" },
  { w: "complain", m: "苦情を言う", ex: "Several customers complained about the delay.", exJa: "数名の顧客が遅延について苦情を言った。" },
  { w: "complete", m: "完了する、完全な", ex: "We completed the renovation last week.", exJa: "私たちは先週改装を完了した。" },
  { w: "concern", m: "懸念、関わる", ex: "Safety is our main concern.", exJa: "安全が私たちの最大の懸念だ。" },
  { w: "conduct", m: "実施する、行う", ex: "The company conducted a customer survey.", exJa: "会社は顧客調査を実施した。" },
  { w: "confirm", m: "確認する", ex: "Please confirm your reservation by Friday.", exJa: "金曜日までに予約を確認してください。" },
  { w: "consider", m: "検討する", ex: "We are considering a new supplier.", exJa: "私たちは新しい仕入先を検討している。" },
  { w: "contract", m: "契約", ex: "Both sides signed the contract yesterday.", exJa: "双方が昨日契約書に署名した。" },
  { w: "convenient", m: "便利な、都合の良い", ex: "The store is convenient for local residents.", exJa: "その店は地元住民にとって便利だ。" },
  { w: "cooperate", m: "協力する", ex: "The two teams cooperated on the design.", exJa: "2つのチームが設計で協力した。" },
  { w: "deadline", m: "締め切り", ex: "The deadline for the report is Monday.", exJa: "報告書の締め切りは月曜日だ。" },
  { w: "decrease", m: "減少する", ex: "Sales decreased slightly in August.", exJa: "8月は売上がわずかに減少した。" },
  { w: "delay", m: "遅延、遅らせる", ex: "The shipment was delayed by bad weather.", exJa: "悪天候で出荷が遅れた。" },
  { w: "deliver", m: "配達する、届ける", ex: "They deliver packages every morning.", exJa: "彼らは毎朝荷物を配達する。" },
  { w: "department", m: "部門、部署", ex: "She works in the marketing department.", exJa: "彼女はマーケティング部で働いている。" },
  { w: "deposit", m: "預金、手付金", ex: "A deposit is required when you book the room.", exJa: "部屋の予約時に手付金が必要だ。" },
  { w: "describe", m: "説明する、描写する", ex: "Please describe the problem in detail.", exJa: "その問題を詳しく説明してください。" },
  { w: "discount", m: "割引", ex: "Members receive a ten percent discount.", exJa: "会員は10%の割引を受けられる。" },
  { w: "distribute", m: "配布する、流通させる", ex: "We distributed samples to every visitor.", exJa: "私たちは来場者全員に試供品を配布した。" },
  { w: "due", m: "期限の、予定の", ex: "The payment is due at the end of the month.", exJa: "支払いは月末が期限だ。" },
  { w: "duty", m: "義務、職務", ex: "It is your duty to lock the office.", exJa: "事務所を施錠するのはあなたの職務だ。" },
  { w: "efficient", m: "効率的な", ex: "The new system is far more efficient.", exJa: "新しいシステムははるかに効率的だ。" },
  { w: "employee", m: "従業員", ex: "The company hired twenty new employees.", exJa: "会社は20人の新しい従業員を雇った。" },
  { w: "encourage", m: "促す、励ます", ex: "We encourage staff to share their ideas.", exJa: "私たちは社員に意見を出すよう促している。" },
  { w: "entire", m: "全体の", ex: "The entire building was repainted.", exJa: "建物全体が塗り直された。" },
  { w: "equipment", m: "設備、機材", ex: "The factory bought new equipment.", exJa: "工場は新しい設備を購入した。" },
  { w: "establish", m: "設立する、確立する", ex: "The firm was established in 1995.", exJa: "その会社は1995年に設立された。" },
  { w: "estimate", m: "見積もる、見積もり", ex: "Can you estimate the total cost?", exJa: "総費用を見積もってもらえますか。" },
  { w: "expand", m: "拡大する", ex: "They plan to expand into Asian markets.", exJa: "彼らはアジア市場への拡大を計画している。" },
  { w: "expense", m: "費用、経費", ex: "Travel expenses will be reimbursed.", exJa: "出張費は払い戻される。" },
  { w: "experience", m: "経験", ex: "She has ten years of experience in sales.", exJa: "彼女は営業で10年の経験がある。" },
  { w: "expert", m: "専門家", ex: "We hired an expert to review the system.", exJa: "私たちはシステムを検査する専門家を雇った。" },
  { w: "extend", m: "延長する、広げる", ex: "They extended the deadline by one week.", exJa: "彼らは締め切りを1週間延長した。" },
  { w: "facility", m: "施設", ex: "The hotel has excellent sports facilities.", exJa: "そのホテルには優れた運動施設がある。" },
  { w: "familiar", m: "よく知っている、見慣れた", ex: "Are you familiar with this software?", exJa: "このソフトには慣れていますか。" },
  { w: "fee", m: "料金、手数料", ex: "There is no fee for the first month.", exJa: "初月は料金がかからない。" },
  { w: "figure", m: "数字、人物", ex: "The sales figures look promising.", exJa: "売上の数字は有望に見える。" },
  { w: "fill out", m: "記入する", ex: "Please fill out this form completely.", exJa: "この用紙にもれなく記入してください。" },
  { w: "forward", m: "転送する、前方へ", ex: "I forwarded your message to the manager.", exJa: "あなたの伝言を部長に転送した。" },
  { w: "furniture", m: "家具", ex: "The office furniture arrived on Tuesday.", exJa: "オフィス家具は火曜日に届いた。" },
  { w: "goods", m: "商品", ex: "The damaged goods were returned.", exJa: "破損した商品は返品された。" },
  { w: "guarantee", m: "保証する、保証", ex: "We guarantee delivery within three days.", exJa: "3日以内の配達を保証します。" },
  { w: "handle", m: "取り扱う、対処する", ex: "She handles complaints from customers.", exJa: "彼女は顧客からの苦情に対処している。" },
  { w: "immediately", m: "直ちに", ex: "Please call the office immediately.", exJa: "直ちに事務所に電話してください。" },
  { w: "improve", m: "改善する", ex: "We improved the packaging design.", exJa: "私たちは包装の設計を改善した。" },
  { w: "increase", m: "増加する、増加", ex: "Demand increased sharply in spring.", exJa: "春に需要が急増した。" },
  { w: "industry", m: "産業、業界", ex: "He has worked in the travel industry for years.", exJa: "彼は長年旅行業界で働いている。" },
  { w: "inspect", m: "検査する", ex: "An officer inspected the warehouse.", exJa: "係官が倉庫を検査した。" },
  { w: "install", m: "設置する", ex: "Technicians will install the printer tomorrow.", exJa: "技術者が明日プリンターを設置する。" },
  { w: "instead", m: "代わりに", ex: "Let's meet on Thursday instead.", exJa: "代わりに木曜日に会いましょう。" },
  { w: "invoice", m: "請求書", ex: "The invoice must be paid within 30 days.", exJa: "請求書は30日以内に支払う必要がある。" },
  { w: "issue", m: "問題、発行する", ex: "We need to resolve this issue quickly.", exJa: "私たちはこの問題を早急に解決する必要がある。" },
  { w: "item", m: "品目、項目", ex: "This item is temporarily out of stock.", exJa: "この品目は一時的に在庫切れだ。" },
  { w: "labor", m: "労働、人手", ex: "Labor costs have risen this year.", exJa: "今年は人件費が上昇した。" },
  { w: "launch", m: "開始する、発売する", ex: "The company launched a new product line.", exJa: "会社は新しい製品群を発売した。" },
  { w: "lease", m: "賃貸借、賃借する", ex: "They signed a five-year lease.", exJa: "彼らは5年の賃貸借契約を結んだ。" },
  { w: "maintain", m: "維持する、保守する", ex: "We maintain the machines every month.", exJa: "私たちは毎月機械を保守している。" },
  { w: "manufacture", m: "製造する", ex: "The parts are manufactured in Thailand.", exJa: "その部品はタイで製造されている。" },
  { w: "measure", m: "測る、対策", ex: "The city took measures to reduce noise.", exJa: "市は騒音を減らす対策を取った。" },
  { w: "negotiate", m: "交渉する", ex: "They negotiated a better price.", exJa: "彼らはより良い価格を交渉した。" },
  { w: "obtain", m: "入手する", ex: "You can obtain a permit at city hall.", exJa: "許可証は市役所で入手できる。" },
  { w: "occupy", m: "占める、使用する", ex: "The meeting room is occupied until noon.", exJa: "その会議室は正午まで使用中だ。" },
  { w: "offer", m: "提供する、申し出", ex: "The store offers free delivery.", exJa: "その店は無料配達を提供している。" },
  { w: "operate", m: "操作する、運営する", ex: "The company operates five factories.", exJa: "その会社は5つの工場を運営している。" },
  { w: "opportunity", m: "機会", ex: "This is a great opportunity for our team.", exJa: "これは我々のチームにとって絶好の機会だ。" },
  { w: "order", m: "注文、注文する", ex: "Your order will ship on Monday.", exJa: "ご注文は月曜日に発送されます。" },
  { w: "organize", m: "準備する、整理する", ex: "She organized the training session.", exJa: "彼女は研修会を準備した。" },
  { w: "participate", m: "参加する", ex: "All staff participated in the workshop.", exJa: "全職員がその講習に参加した。" },
  { w: "performance", m: "業績、公演", ex: "The team's performance improved greatly.", exJa: "チームの業績は大きく向上した。" },
  { w: "permit", m: "許可する、許可証", ex: "Smoking is not permitted in this area.", exJa: "この区域では喫煙は許可されていない。" },
  { w: "policy", m: "方針、政策", ex: "Our return policy allows refunds for 30 days.", exJa: "当社の返品方針では30日間返金が可能だ。" },
  { w: "postpone", m: "延期する", ex: "The concert was postponed until June.", exJa: "そのコンサートは6月まで延期された。" },
  { w: "prefer", m: "好む", ex: "Most customers prefer the smaller size.", exJa: "ほとんどの客は小さいサイズを好む。" },
  { w: "prepare", m: "準備する", ex: "He prepared a summary for the board.", exJa: "彼は役員会向けの要約を準備した。" },
  { w: "previous", m: "以前の", ex: "The previous manager retired last year.", exJa: "前の部長は昨年退職した。" },
  { w: "process", m: "工程、処理する", ex: "We are processing your application now.", exJa: "現在あなたの申請を処理しています。" },
  { w: "profit", m: "利益", ex: "The store made a small profit last month.", exJa: "その店は先月わずかな利益を上げた。" },
  { w: "promote", m: "昇進させる、販売促進する", ex: "She was promoted to regional manager.", exJa: "彼女は地域部長に昇進した。" },
  { w: "propose", m: "提案する", ex: "He proposed a simpler solution.", exJa: "彼はより単純な解決策を提案した。" },
  { w: "provide", m: "提供する", ex: "The hotel provides free breakfast.", exJa: "そのホテルは無料の朝食を提供している。" },
  { w: "purchase", m: "購入する、購入", ex: "Keep your receipt after every purchase.", exJa: "購入のたびに領収書を保管してください。" },
  { w: "quality", m: "品質", ex: "Customers praised the quality of the fabric.", exJa: "顧客はその生地の品質を称賛した。" },
  { w: "quantity", m: "数量", ex: "Please indicate the quantity you need.", exJa: "必要な数量を記入してください。" },
  { w: "receipt", m: "領収書、受領", ex: "Bring your receipt for a refund.", exJa: "返金には領収書をお持ちください。" },
  { w: "recommend", m: "推薦する、勧める", ex: "I recommend the earlier flight.", exJa: "私は早い方の便を勧める。" },
  { w: "reduce", m: "減らす", ex: "We reduced waste by half.", exJa: "私たちは廃棄物を半分に減らした。" },
  { w: "refund", m: "払い戻し", ex: "You can request a full refund.", exJa: "全額の払い戻しを請求できる。" },
  { w: "register", m: "登録する", ex: "Please register at the front desk.", exJa: "受付で登録してください。" },
  { w: "reject", m: "却下する、拒否する", ex: "The committee rejected the proposal.", exJa: "委員会はその提案を却下した。" },
  { w: "relocate", m: "移転する", ex: "The head office relocated to Nagoya.", exJa: "本社は名古屋に移転した。" },
  { w: "remind", m: "思い出させる", ex: "Please remind me about the meeting.", exJa: "会議のことを思い出させてください。" },
  { w: "renew", m: "更新する", ex: "You should renew your passport soon.", exJa: "そろそろパスポートを更新すべきだ。" },
  { w: "repair", m: "修理する", ex: "The elevator is being repaired today.", exJa: "エレベーターは今日修理中だ。" },
  { w: "replace", m: "交換する、取って代わる", ex: "We replaced the old printer.", exJa: "私たちは古いプリンターを交換した。" },
  { w: "request", m: "依頼する、要求", ex: "She requested additional information.", exJa: "彼女は追加の情報を依頼した。" },
  { w: "require", m: "必要とする", ex: "This job requires strong writing skills.", exJa: "この仕事は高い文章力を必要とする。" },
  { w: "reserve", m: "予約する", ex: "I reserved a table for four.", exJa: "4名のテーブルを予約した。" },
  { w: "responsible", m: "責任がある", ex: "He is responsible for the schedule.", exJa: "彼は日程に責任がある。" },
  { w: "retail", m: "小売", ex: "The retail price is twenty dollars.", exJa: "小売価格は20ドルだ。" },
  { w: "revenue", m: "収益、歳入", ex: "Annual revenue rose by five percent.", exJa: "年間収益は5%増加した。" },
  { w: "schedule", m: "予定、予定を組む", ex: "The meeting is scheduled for Friday.", exJa: "会議は金曜日に予定されている。" },
  { w: "shipment", m: "出荷、積荷", ex: "The shipment arrived two days early.", exJa: "積荷は2日早く到着した。" },
  { w: "sign up", m: "申し込む、登録する", ex: "Twenty people signed up for the class.", exJa: "20人がその講座に申し込んだ。" },
  { w: "staff", m: "職員、スタッフ", ex: "The staff were very helpful.", exJa: "職員はとても親切だった。" },
  { w: "submit", m: "提出する", ex: "Submit your report by noon.", exJa: "正午までに報告書を提出してください。" },
  { w: "supply", m: "供給する、供給", ex: "They supply parts to several factories.", exJa: "彼らは複数の工場に部品を供給している。" },
  { w: "survey", m: "調査、調査する", ex: "The survey showed high satisfaction.", exJa: "その調査は高い満足度を示した。" },
  { w: "temporary", m: "一時的な", ex: "This is only a temporary solution.", exJa: "これは一時的な解決策にすぎない。" },
  { w: "traffic", m: "交通、交通量", ex: "Traffic was heavy on the highway.", exJa: "高速道路は交通量が多かった。" },
  { w: "transfer", m: "移す、転勤する", ex: "He transferred to the Tokyo office.", exJa: "彼は東京事務所に転勤した。" },
  { w: "urgent", m: "緊急の", ex: "This is an urgent matter.", exJa: "これは緊急の案件だ。" },
  { w: "vehicle", m: "車両、乗り物", ex: "Company vehicles are parked in back.", exJa: "社用車は裏に駐車してある。" },
  { w: "warehouse", m: "倉庫", ex: "The goods are stored in the warehouse.", exJa: "その商品は倉庫に保管されている。" },
  { w: "warranty", m: "保証(書)", ex: "The laptop comes with a two-year warranty.", exJa: "そのノートパソコンには2年保証が付く。" },
];
